branch-defaults:
  master:
    environment: sqsd-handler-demo
global:
  application_name: sqsd-handler-demo
  default_ec2_keyname: null
  default_platform: 64bit Amazon Linux 2015.03 v1.4.1 running Node.js
  default_region: us-west-2
  profile: null
  sc: git
